### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by danyfedorov** [bugdie4k/rnbw#1]
Examples
10
![screen_2017-11-04_21-00-00_selection_w1210-h693](https://user-images.githubusercontent.com/22116479/32408585-2fb972c4-c1a3-11e7-838e-767d602c722f.png)
9
![screen_2017-11-04_20-53-43_selection_w1206-h691](https://user-images.githubusercontent.com/22116479/32408542-49af48b2-c1a2-11e7-9579-ba5389b047fc.png)
8
![screen_2017-11-04_20-43-40_selection_w1208-h691](https://user-images.githubusercontent.com/22116479/32408473-018e16cc-c1a1-11e7-8258-5497e2f09b12.png)
7
![screen_2017-11-04_05-48-54_selection_w1209-h693](https://user-images.githubusercontent.com/22116479/32402014-f2a622b2-c123-11e7-9744-f0d512858e11.png)
6
![screen_2017-11-04_05-48-03_selection_w1206-h690](https://user-images.githubusercontent.com/22116479/32402015-f2c21134-c123-11e7-97da-d0e1b7675ce8.png)
5
![screen_2017-11-04_05-47-49_selection_w1208-h691](https://user-images.githubusercontent.com/22116479/32402016-f2dafcda-c123-11e7-9d57-fb2b46ed7dc1.png)
4
![screen_2017-11-04_05-47-24_selection_w1205-h689](https://user-images.githubusercontent.com/22116479/32402017-f2f3f67c-c123-11e7-99da-712c791fb6ad.png)
3
![screen_2017-11-04_05-47-01_selection_w1206-h692](https://user-images.githubusercontent.com/22116479/32402018-f30d32fe-c123-11e7-9064-b6ed20ae7f7f.png)
2
![screen_2017-11-04_05-45-59_selection_w1207-h691](https://user-images.githubusercontent.com/22116479/32402019-f3279a68-c123-11e7-9d36-b7c98f4274e9.png)
1
![screen_2017-11-04_05-45-23_selection_w1207-h693](https://user-images.githubusercontent.com/22116479/32402020-f3403fb4-c123-11e7-95da-d0e416a630c5.png)
0
![screen_2017-11-04_05-44-55_selection_w1209-h692](https://user-images.githubusercontent.com/22116479/32402021-f3596bb0-c123-11e7-9e37-d4c3c4eb6215.png)

**Comment by bugdie4k** [comment]
![screen_2017-10-22_22-47-10_selection_w1365-h601](https://user-images.githubusercontent.com/22116479/31865653-f8eb84ee-b77a-11e7-8eba-d525361bd31c.png)

**Comment by bugdie4k** [comment]
![screen_2017-10-22_22-53-01_selection_w1365-h716](https://user-images.githubusercontent.com/22116479/31865708-c9d80e06-b77b-11e7-86c5-a4d29a984ce7.png)

**Comment by bugdie4k** [comment]
![screen_2017-10-22_23-12-25_selection_w1365-h621](https://user-images.githubusercontent.com/22116479/31865856-8a9e1a52-b77e-11e7-9c83-1cc85f7421ea.png)

**Comment by danyfedorov** [comment]
![screen_2017-11-04_07-13-01_selection_w1211-h681](https://user-images.githubusercontent.com/22116479/32402606-98d1647e-c130-11e7-9558-a5501df6fc79.png)
![screen_2017-11-04_21-17-41_selection_w1220-h600](https://user-images.githubusercontent.com/22116479/32408701-b123d640-c1a5-11e7-9979-086074434a53.png)
